version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '8080:8080'
    volumes:
      - ./backend:/usr/src/app
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=production
    ports:
      - '3000:3000'
    volumes:
      - ./frontend:/usr/src/app